hmcts/sscs-hearings-api

Jenkinsfile_CNP, Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/SSCS-10152
```
[ ] Yes
[x] No
```
=> SSCS-10152 Temporarily disable mutation tests.

build.gradle, security.sh
=> Sscs 10229 address nightly build issues

src/main/java/uk/gov/hmcts/reform/sscs/controllers/ServiceHearingsController.java, src/main/java/uk/gov/hmcts/reform/sscs/exception/CaseException.java, src/main/java/uk/gov/hmcts/reform/sscs/exception/GetCaseException.java, src/main/java/uk/gov/hmcts/reform/sscs/exception/UpdateCaseException.java, src/main/java/uk/gov/hmcts/reform/sscs/service/CcdCaseService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/AuthorisationServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/CcdCaseServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10224
Implementing:
```
[ ] Yes
[x] No
```
=> SSCS-10224 getCaseDetails Method

Jenkinsfile_CNP, charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.preview.template.yaml, charts/sscs-hearings-api/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCS-10218
This PR contains environment files configuration changes required for the clients to access Caseworker reference data API 
Note: The actual caseworker reference data feign clients are in `SSCS-Common` library.
```
[ ] Yes
[x] No
```
=> SSCS-10218 staff reference interface

build.gradle, config/checkstyle/checkstyle.xml, src/main/java/uk/gov/hmcts/reform/sscs/exception/UnhandleableHearingState.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/HearingsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/model/HearingState.java, src/main/java/uk/gov/hmcts/reform/sscs/model/HearingWrapper.java, src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/helper/HearingsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10225
The skeleton of the Case Details to HMC mapping. It will be the basis to be completed by other tickets.
```
[ ] Yes
[x] No
```
=> SSCS-10225 Case Details to HMC Mapping 

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10376
```
[ ] Yes
[ ] No
```
=> SSCS-10376 Fix builds

build.gradle, charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml, infrastructure/service-bus.tf
=> SSCS-10278 Change subscription name, fix interpolation.

charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml
=> SSCS-10278 Update values.yaml with hmc connection secret.

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/sscs/consumer/GetHearingPactConsumerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/exceptions/FeignClientErrorDecoderIntegrationTest.java, src/integrationTest/resources/application-integration.yaml, src/main/java/uk/gov/hmcts/reform/sscs/config/FeignClientConfig.java, src/main/java/uk/gov/hmcts/reform/sscs/service/exceptions/FeignClientErrorDecoder.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/service/exceptions/FeignClientErrorDecoderTest.java
https://tools.hmcts.net/jira/browse/SSCS-10275
Let me know if the following feign config are fine:
client:
config:
default:
connectTimeout: 10000
readTimeout: 10000
loggerLevel: full
retryer:
period: 500
maxPeriod: 2000
maxAttempts: 3
```
[ ] Yes
[ x ] No
```
=> Sscs 10275 failed hmc call processing

src/contractTest/java/uk/gov/hmcts/reform/sscs/ContractTestDataProvider.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/IndividualDetails.java
https://tools.hmcts.net/jira/browse/SSCS-10465
```
[ ] Yes
[X] No
```
=> Remove title

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10388
```
[x] Yes
[ ] No
```
=> SSCS-10388 Update Commons

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java, src/main/resources/application.yaml
=> Log Additions

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10444
```
[ ] Yes
[X] No
```
=> SSCS-10444 updating build.gradle

charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml
=> SSCS-10220 Bump chart version, add resource group to secrets.

charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml, src/main/resources/application.yaml
=> SSCS-10220 Fix AppInsights key

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml, src/main/resources/application.yaml
=> SSCS-10220 Add sscs secret mount path, aliases.

src/integrationTest/java/uk/gov/hmcts/reform/sscs/config/SwaggerPublisherTest.java, src/main/java/uk/gov/hmcts/reform/sscs/HearingsApiApplication.java, src/main/java/uk/gov/hmcts/reform/sscs/exception/ClientAuthorisationException.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsCaseMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/model/HearingWrapper.java, src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsCaseMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsMappingBase.java
https://tools.hmcts.net/jira/browse/SSCS-10321
```
[ ] Yes
[x] No
```
=> SSCS-10321 Fixes

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/ServiceHearingsControllerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/controllers/ServiceHearingsController.java, src/main/java/uk/gov/hmcts/reform/sscs/model/service/ServiceHearingRequest.java
https://tools.hmcts.net/jira/browse/SSCS-10262
```
[ ] Yes
[x] No
```
=> SSCS-10262 Fix ServiceLinkedCases request

config/owasp/suppressions.xml
Suppressing Spring Dependency due to no available build without it.
=> Suppress spring issue

build.gradle
=> SSCS-10552-Upgrade-Tomcat: upgrade tomcat

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10281
```
[ ] Yes
[x] No
```
=> SSCS-10281 Linked Cases Logic

build.gradle, charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMappingTest.java
=> SSCS-10547 Update reference data.

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsCaseMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/CaseCategory.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsCaseMappingTest.java
=> SSCS-10430 Update CaseCategory object.

build.gradle, config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/ServiceHearingsControllerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/config/SecurityConfiguration.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java, src/test/resources/serviceHearingValuesForControllerTest.json
=> Upgrade SpringFramework, Fix Vunerability Issues and Bugged Intergration Test

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsAutoListMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/PartyFlagsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsAutoListMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10135
```
[ ] Yes
[x] No
```
=> SSCS-10135 Autolist Flag

charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml, src/main/java/uk/gov/hmcts/reform/sscs/config/jms/HearingsJmsConfig.java
=> SSCS-10579 Add key vault mount.

charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml
=> SSCS-10579 Fix environment variable

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/HearingWindow.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java, src/test/resources/serviceHearingValues.json, src/test/resources/serviceHearingValuesForControllerTest.json
=> SSCS-10617 QA Test Branch

src/main/java/uk/gov/hmcts/reform/sscs/config/FeignClientConfig.java, src/main/java/uk/gov/hmcts/reform/sscs/model/hmc/message/HmcMessage.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/HearingDetails.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCS-10286
```
[ ] Yes
[x] No
```
=> SSCS-10286 Jackson Feature Fix

src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/IndividualDetails.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCS-10286
```
[ ] Yes
[x] No
```
=> SSCS-10286 Jackson Ignore Property Case and Re-add Title

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java, src/test/resources/serviceHearingValuesForControllerTest.json
https://tools.hmcts.net/jira/browse/SSCS-10642
```
[ ] Yes
[x] No
```
=> SSCS-10642 HearingPriority Reference Data Update

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10378
Hearings API - Joint Party Mapping
Changes for master from PR: https://github.com/hmcts/sscs-hearings-api/pull/127
```
[ ] Yes
[x ] No
```
=> SSCS-10378 Pushing changes to new PR

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java, src/test/resources/serviceHearingValuesForControllerTest.json
=> SSCS-10642 Update hearing priority type.

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10643
```
[ ] Yes
[X] No
```
=> SSCS-10643 Fix tests

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10655
```
[ ] Yes
[ ] No
```
=> SSCS-10655 Ensure unavailability type is set in party mapping.

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10260
```
[ ] Yes
[x] No
```
=> SSCS-10620 Demo Commons Bump

src/main/java/uk/gov/hmcts/reform/sscs/jms/listener/HmcHearingsEventTopicListener.java
=> SSCS-10286 Improve hmc topic logging.

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10178
```
[ ] Yes
[x] No
```
=> SSCS-10178 Filter By Venue

src/main/java/uk/gov/hmcts/reform/sscs/controllers/ServiceHearingsController.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsService.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10635
```
[ ] Yes
[x] No
```
=> SSCS-10635 ServiceHearingValues Case Updates

src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10242
```
[ ] Yes
[ ] No
```
=> SSCS-10242 Use HMC status over ListAssistCaseStatus

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10559
```
[ ] Yes
[ ] No
```
=> SSCS-10559 Fix override duration.

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateServiceTest.java
=> Sscs 10242 revert work basket changes master

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10643
```
[ ] Yes
[ ] No
```
=> SSCS-10643 - Reference Data Update

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/ServiceHearingsControllerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/controllers/ServiceHearingsController.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsCaseMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/LinkedCasesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/jms/listener/HmcHearingsEventTopicListener.java, src/main/java/uk/gov/hmcts/reform/sscs/model/service/linkedcases/LinkedCase.java, src/main/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsService.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/LinkedCasesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10644
Update serviceLinkedCase endpoint to include caseName and reasonsForLink
```
[ ] Yes
[x] No
```
=> Sscs 10644 update service linked cases

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10242
```
[ ] Yes
[x] No
```
=> SSCS-10242 Hearing Date Filter

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/ServiceHearingsControllerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/controllers/ServiceHearingsController.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/LinkedCasesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/model/service/linkedcases/ServiceLinkedCases.java, src/main/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsService.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/LinkedCasesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10644
Removing Linked Cases label from the endpoint response
```
[ ] Yes
[x] No
```
=> SSCS-10644-Update-Linked-Cases: remove LinkedCases from response

src/contractTest/java/uk/gov/hmcts/reform/sscs/ContractTestDataProvider.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsAdjustmentMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingPartiesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/model/hmc/reference/Adjustment.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/IndividualDetails.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsAdjustmentMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10667
```
[ ] Yes
[x] No
```
=> SSCS-10667 Moving Reasonable Adjustments from facilities required

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingPartiesMapping.java
https://tools.hmcts.net/jira/browse/SSCS-10659
```
[ ] Yes
[x] No
```
=> SSCS-10659 Temporarily Remove DWP Party in SHV

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsNumberAttendeesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsNumberAttendeesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10680
```
[ ] Yes
[x] No
```
=> SSCS-10680 Number of Physical Attendees

config/owasp/suppressions.xml
=> Fix dependency issues

charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml
https://tools.hmcts.net/jira/browse/SSCS-10651
```
[ ] Yes
[X] No
```
=> SSCS-10651 Fix Azure Error

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10708
```
[ ] Yes
[x] No
```
=> SSCS-10708 Commons Bump

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/sscs/ContractTestDataProvider.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/HearingDetails.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10598
```
[ ] Yes
[x] No
```
=> SSCS-10598 Amending Hearing Request

Jenkinsfile_CNP
=> SSCS-10742 Remove branch syncs

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10706
Cardiff LA commons bump
```
[ ] Yes
[x] No
```
=> Cardiff-LA-commons-bump

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/projects/SSCS/issues/SSCS-10746?filter=allopenissues
```
[ ] Yes
[ ] No
```
=> SSCS-10746-cve-suppression

src/main/java/uk/gov/hmcts/reform/sscs/HearingsApiApplication.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/model/multi/hearing/CaseHearing.java, src/main/java/uk/gov/hmcts/reform/sscs/model/multi/hearing/HearingsGetResponse.java, src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/HmcHearingsApi.java, src/main/java/uk/gov/hmcts/reform/sscs/service/HmcHearingsApiService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceRetryTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10676
```
[ ] Yes
[x] No
```
=> SSCS-10676 Duplication of Hearings After HMC Request Fix

config/owasp/suppressions.xml
=> extend suppression dates

src/main/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsService.java
=> SSCS-10776 Fix logging.

build.gradle, config/owasp/suppressions.xml
https://github.com/hmcts/sscs-track-your-appeal-notifications/pull/2148
```
[ ] Yes
[ ] No
```
=> SSCS-10805-update-jar-version

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMapping.java
https://tools.hmcts.net/jira/browse/SSCS-10773
Hearing channel fields are not displayed within "Listing Requirements" tab
```
[ ] Yes
[x ] No
```
=> SSCC-10773: adding logs for override fields for testing

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java
=> SSCS-10773 Revert initial changes.

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMapping.java
Rollback logs in OverrideMapping.class
```
[ ] Yes
[x ] No
```
=> SSCS-rollback_logs: reverted logs in OverrideMapping.class

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsServiceTest.java
=> SSCS-10841 Common bump

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingPartiesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10810
Updates in hearing api to check for INTERPRETER role and process accordingly for HearingsDetailsMappings
```
[ ] Yes
[x] No
```
=> SSCS-10810 - Don't send relatedParties payload for Appointees, Jp's & Other parties

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java
Reverts hmcts/sscs-hearings-api#307
=> Revert "SSCS-10332 - Ability to book hearings for 'paper' cases to any venue within the same region as the RPC"

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsServiceTest.java
This reverts commit 346d70b62f57ebec6c734416286fce3c985788d1.
```
[ ] Yes
[ ] No
```
=> Revert "SSCS-10841 Common bump (#317)"

build.gradle, config/owasp/suppressions.xml, src/contractTest/java/uk/gov/hmcts/reform/sscs/ContractTestDataProvider.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsChannelMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsEventMappers.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsWindowMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/model/hmc/reference/HearingType.java, src/main/java/uk/gov/hmcts/reform/sscs/model/hmc/reference/HmcStatus.java, src/main/java/uk/gov/hmcts/reform/sscs/model/service/hearingvalues/ServiceHearingValues.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/HearingDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/HearingResponse.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/RequestDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageService.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsChannelMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsEventMappersTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsWindowMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageServiceTest.java, src/test/resources/serviceHearingValues.json
https://tools.hmcts.net/jira/browse/SSCS-10818
https://tools.hmcts.net/jira/browse/SSCS-10798
```
[x] Yes
[ ] No
```
=> 10818,10798 PR

.github/dependabot.yml, .github/renovate.json
https://tools.hmcts.net/jira/browse/SSCS-10901
```
[ ] Yes
[ ] No
```
=> SSCS-10901 Configure renovate

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsAutoListMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsCaseMapping.java
[SSCS-10889](https://tools.hmcts.net/jira/projects/SSCS/issues/SSCS-10889)
- New log message when an incorrect benefit/issue code combination is used, intended to clarify what would otherwise cause a NullPointerException soon afterwards.
- Update of snakeyaml library version to fix a CVE
- Removal of unnecessary CVE suppressions
- Assessment on remaining CVE with related update of suppression date and reason
```
[ ] Yes
[ X ] No
```
=> SSCS-10889 Improve logging

src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10177
=> SSCS-10177 Fix dwp state

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsChannelMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingPartiesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsChannelMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsNumberAttendeesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCS-10891
```
[ ] Yes
[x] No
```
=> SSCS-10891 DWP Party as Individual

src/main/java/uk/gov/hmcts/reform/sscs/service/holder/ReferenceDataServiceHolder.java, src/main/resources/application.yaml
n/a
Adds feature flag for Adjournment to application.yaml and a boolean in ReferenceDataServiceHolder for use
```
[ ] Yes
[ x ] No
```
=> Adds adjournment feature flag

build.gradle, config/owasp/suppressions.xml
SSCS-10910
Update of snakeyaml library (was: suppression of not-applicable vulnerability)
```
[ ] Yes
[x] No
```
=> SSCS-10910

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10968
```
[ ] Yes
[ ] No
```
=> SSCS-10968 cve suppression

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10985
```
[ ] Yes
[x] No
```
=> SSCS-10985 CVE Fix Commons Bump

infrastructure/service-bus.tf
SSCS-11008
Add content type and tags to secrets
```
[ ] Yes
[ x ] No
```
=> SSCS-11008 - Add content type and tags to secrets

charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml
=> SSCS-10924 Enable secret

build.gradle, config/owasp/suppressions.xml
=> updates jackson databind to latest 2.14.0-rc3

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsEventMappers.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/service/CcdCaseService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsEventMappersTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelperTest.java
https://tools.hmcts.net/jira/browse/SSCS-10853
```
[ ] Yes
[x] No
```
=> SSCS-10853 Hearing Postponed Event Change

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsCaseMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/PartyFlagsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/service/holder/ReferenceDataServiceHolder.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsCaseMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMappingAdjournmentTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsMappingBase.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/PartyFlagsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-11092
https://tools.hmcts.net/jira/browse/SSCS-10294
Imports new common change of separate Adjournment class in SscsCaseData
Also includes changes for hearing duration 10294
```
[ ] Yes
[ x ] No
```
=> Sscs 11092 updates hearings to new adjournment common

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsAutoListMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsCaseMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPanelMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/model/hmc/reference/HmcStatus.java
https://tools.hmcts.net/jira/browse/SSCS-11325
Hmc status exceptions should throw handling error, not listing error
```
[ ] Yes
[x] No
```
=> SSCS-11325 listing error

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/HearingDetails.java
SSCS-11359
```
[ ] Yes
[ ] No
```
=> change duration to integer from number

build.gradle
=> upgrade dependencycheck to v8

src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageServiceTest.java
=> SSCS-11420 : Removed LA to HMC status comparison

build.gradle
=> Upgrade renovate

build.gradle
Reverts hmcts/sscs-hearings-api#442
=> Revert "Update dependency org.slf4j:slf4j-api to v2"

.github/workflows/ci.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> renovate v1

src/main/java/uk/gov/hmcts/reform/sscs/jms/listener/TribunalsHearingsEventQueueListener.java
=> SSCS-11537 : Remove sleep statement from hearings event queue

src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java
=> SSCS-11516 : Remove invalid case states

config/owasp/suppressions.xml
uncontrolled
```
[ ] Yes
[ ] No
```
=> add suppressions

build.gradle, config/owasp/suppressions.xml
CVE fix for supressed issues
```
[ ] Yes
[x] No
```
=> CVE-05.04.23

build.gradle
CVE Fix - Spring framework update to 5.3.27
```
[ ] Yes
[x] No
```
=> CVEFix-24.04.23

build.gradle, config/owasp/suppressions.xml
CVE Supression - 02.05.2023
```
[ ] Yes
[x] No
```
=> CVEFix-02.05.2023

build.gradle, config/owasp/suppressions.xml
CVE Suppression 01.06.2023
```
[ ] Yes
[x] No
```
=> CVE Suppression 01.06.2023

build.gradle
CVE Fix - 12.06.2023
```
[ ] Yes
[x] No
```
=> CVE Fix - 12.06.2023

config/owasp/suppressions.xml
CVE Fix - 27.06.2023
```
[ ] Yes
[x] No
```
=> CVE Fix - 27.06.2023

config/owasp/suppressions.xml
CVE Fix - 30.06.2023
```
[ ] Yes
[x] No
```
=> CVE Fix - 30.06.2023

build.gradle, config/owasp/suppressions.xml
CVE Fix 31.07.2023
```
[ ] Yes
[x] No
```
=> CVE Fix 31.07.2023

src/main/resources/application.yaml
uncontrolled
```
[ ] Yes
[ ] No
```
=> nremove flags

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/sscs/ContractTestDataProvider.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/exceptions/FeignClientErrorDecoderIntegrationTest.java, src/integrationTest/resources/application-integration.yaml, src/integrationTest/resources/config/application_it.properties, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/HearingDaySchedule.java, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/holder/ReferenceDataServiceHolder.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsWindowMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateServiceTest.java
=> Sscs 11339 remit to first tier

src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/RequestDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-12009
Made versionNumber mandatory for json
```
[ ] Yes
[x] No
```
=> SSCS-12009: Made versionNumber mandatory for json

src/main/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsService.java
https://tools.hmcts.net/jira/browse/SSCS-12077
Jsr310 fix
```
[ ] Yes
[x] No
```
=> Jsr310 fix

build.gradle, charts/sscs-hearings-api/Chart.yaml, config/owasp/suppressions.xml
=> Update Hearings API suppressions

config/owasp/suppressions.xml
Update suppressions file with new cve
=> SSCS - Update Suppressions

build.gradle
dependency check upgrade to 9.0.6
=> dependency check upgrade

README.md
Updated readme to kick-off pipeline build
=> Empty commit

src/main/resources/application.yaml
=> SSCSCI-529: Add deployment id

src/main/java/uk/gov/hmcts/reform/sscs/jms/listener/HmcHearingsEventTopicListener.java, src/test/java/uk/gov/hmcts/reform/sscs/jms/listener/HmcHearingsEventTopicListenerTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-529
Rename deployment ID for deployment filter
```
[ ] Yes
[x ] No
```
=> SSCSCI-529 : Rename deployment id

src/main/java/uk/gov/hmcts/reform/sscs/jms/listener/HmcHearingsEventTopicListener.java, src/test/java/uk/gov/hmcts/reform/sscs/jms/listener/HmcHearingsEventTopicListenerTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-529
Update hearing filter
```
[ ] Yes
[ ] No
```
=> SSCSCI-529: Update hearing filter

src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMappingTest.java
=> SSCS-12063 - Revert video email changes

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java
=> Fix common bump

build.gradle, charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.preview.template.yaml, charts/sscs-hearings-api/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCSSI-156 
Cannot see references to orchestrator.
```
[ ] Yes
[x] No
```
=> SSCSSI-156 Remove references for unused orchestrator

charts/sscs-hearings-api/Chart.yaml, charts/sscs-hearings-api/values.yaml
https://tools.hmcts.net/jira/browse/SSCSCI-499
```
[ ] Yes
[ ] No
```
=> SSCSCI-499: upgrade java chart

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsWindowMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsWindowMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java
- https://tools.hmcts.net/jira/browse/SSCSCI-831
- delay hearing window start date from 28 to 31 days
```
[ ] Yes
[X] No
```
=> SSCSCI-831: delay hearing window start date from 28 to 31 days

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsNumberAttendeesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingPartiesMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDetailsMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsNumberAttendeesMappingTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingValuesMappingTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-759
Filter out other party if hearing options is not present
```
[ ] Yes
[X] No
```
=> SSCSCI-759: Handle other party hearingOptions NPE

build.gradle
=> update sscs-common to 5.9.0

src/main/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/model/hmc/message/HearingUpdate.java, src/main/java/uk/gov/hmcts/reform/sscs/model/hmc/reference/HmcStatus.java, src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/HearingSubChannel.java, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageService.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelperTest.java
https://tools.hmcts.net/jira/browse/SSCS-12408
https://tools.hmcts.net/jira/browse/SSCS-12230
changed event when updating hearing
```
[ ] Yes
[ ] No
```
=> changed event when updating hearing

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-957
Updated file path
```
[ ] Yes
[x] No
```
=> Sonarqube test coverage fix

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-1004
- common version bump to update huddersfield venue address
```
[ ] Yes
[X] No
```
=> common version bump to update huddersfield/blackpool venues

build.gradle
=> SSCSSI-313 & SSCSSI-315: Fix broken trigger in Issue further evidence

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsService.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java
- See [SSCSCI-1028](https://tools.hmcts.net/jira/browse/SSCSCI-1028)
- use mrdReference/dialect lookup logic from common
```
[ ] Yes
[X] No
```
=> SSCSCI-1028: use lang ref lookup logic from common

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMapping.java, src/main/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsService.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java
Reverts hmcts/sscs-hearings-api#643
=> Revert "SSCSCI-1028: use lang ref lookup logic from common"
